version: '2'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=sqlpassword
    volumes:
      - booked-database:/var/lib/mysql

  php:
    build: ./php
    volumes:
      - ./booked:/booked
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

  web:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./booked:/booked
    ports:
      - 80:80
    depends_on:
      - php

volumes:
  booked-database:
